### ISSUE TITLE
Failed to conduct wallet operation

### ISSUE THREAD

**Issue by anipy1** [LtbLightning/ldk-node-flutter#22]
I am encountering an error while attempting to execute the [onChainBalance](https://github.com/LtbLightning/ldk-node-flutter-demo/blob/master/lib/screens/home.dart#L66) method in the [ldk_node_flutter_demo](https://github.com/LtbLightning/ldk-node-flutter-demo) project,  it results in an unhandled exception with the following error message:

```text
/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Failed to conduct wallet operation., null)
E/flutter: #0 FlutterRustBridgeBase._transformRust2DartMessage basic.dart:129
E/flutter: #1 FlutterRustBridgeBase.executeNormal.<anonymous closure> basic.dart:70
E/flutter: <asynchronous suspension>
E/flutter: #2 _HomeState.onChainBalance screens.dart:77
E/flutter: <asynchronous suspension>
```

Here is the output of flutter doctor on my development machine:

```
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.2283])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources
```

The error occurred on the Android Emulator Nexus 5X API 30.

I would appreciate any guidance or suggestions on resolving this issue. Thank you!

**Comment by BitcoinZavior** [comment]
@aniketambore This resembles a sync issue? Is the esplora url and port specified correctly? And is it for testnet or mainnet?

**Comment by anipy1** [comment]
Thanks for your response @BitcoinZavior. Yes, I am testing this on the Testnet network. To address the issue, I made modifications to the `buildNode` method in the demo project as follows:

```dart
  buildNode(String mnemonic) async {
    final directory = await getApplicationDocumentsDirectory();
    final ipAddr = await IpAddress.getIpv4();
    final storagePath = "${directory.path}/$LDK_NODE_DIR";
    const esploraUrl = "https://blockstream.info/testnet/api/";
    final builder = ldk.Builder()
        .setEntropyBip39Mnemonic(mnemonic: ldk.Mnemonic(internal: mnemonic))
        .setListeningAddress(ldk.NetAddress.iPv4(addr: ipAddr, port: 9735))
        .setNetwork(ldk.Network.testnet)
        .setStorageDirPath(storagePath)
        .setEsploraServer(esploraServerUrl: esploraUrl);
    ldkNode = await builder.build();
    await start();
    await getListeningAddress();
  }
```

With these modifications, the app successfully starts, and I can input the mnemonic in the TextFormField. However, when I click the "Start Node" button to display the Home content, the application abruptly quits and shows an error like this:

```text
F/libc (5299): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5479 (tokio-runtime-w), pid 5299 (de_flutter_demo)
...
Abort message: 'Failed to bind to listen address/port - is something else already listening on it?'
```

In response to this error, I modified the `buildNode` method to its original state, where I kept the address and port as they were, in the regtest environment. I only modified the Esplora URL and network, as I think the address and port are used for connecting nodes as direct peers and for constructing payment channels. Here's the modified method:

```dart
  buildNode(String mnemonic) async {
    final directory = await getApplicationDocumentsDirectory();
    final storagePath = "${directory.path}/$LDK_NODE_DIR";
    const esploraUrl = "https://blockstream.info/testnet/api/";
    final builder = ldk.Builder()
        .setEntropyBip39Mnemonic(mnemonic: ldk.Mnemonic(internal: mnemonic))
        .setListeningAddress(ldk.NetAddress.iPv4(addr: '127.0.0.1', port: 3004))
        .setNetwork(ldk.Network.testnet)
        .setStorageDirPath(storagePath)
        .setEsploraServer(esploraServerUrl: esploraUrl);
    ldkNode = await builder.build();
    await start();
    await getListeningAddress();
  }
```

With this modified method, I can successfully retrieve the on-chain funding address. However, when I click on the on-chain balance, it displays the error: 
```text
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Failed to conduct wallet operation., null).
```

I think there may be an issue with my node setup. Any guidance on resolving this issue would be greatly appreciated. Thanks!

**Comment by BitcoinZavior** [comment]
Can you try using a different storage location and check? There is a known issue where reusing the storage location is causing an error.
And also check if you are able access the esplora url and port that you are using.
And see the logs to check if you are getting rate limited by blockstream with 429 errors.

**Comment by anipy1** [comment]
I made some changes to the `buildNode` method by modifying the storage location, and it worked. Below is the modified method for reference:

```dart
buildNode(String mnemonic) async {
  final directory = await getApplicationSupportDirectory();
  final storagePath = "${directory.path}/noob";
  const esploraUrl = "https://blockstream.info/testnet/api";
  final builder = ldk.Builder()
      .setEntropyBip39Mnemonic(mnemonic: ldk.Mnemonic(internal: mnemonic))
      .setListeningAddress(ldk.NetAddress.iPv4(addr: '127.0.0.1', port: 9735))
      .setNetwork(ldk.Network.testnet)
      .setStorageDirPath(storagePath)
      .setEsploraServer(esploraServerUrl: esploraUrl);
  ldkNode = await builder.build();
  await start();
  await getListeningAddress();
}
```

With this modification, I was able to retrieve the total on-chain balance successfully. However, after obtaining the balance, I encountered the same error. When clicking on the "On Chain Balance" button, the error persisted, even though it initially worked once and then continued to throw the same error:

```
I/flutter (5856): [+] Wallet onchain balance: 5027526
E/flutter (5856): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Failed to conduct wallet operation., null)
E/flutter (5856): #0 FlutterRustBridgeBase._transformRust2DartMessage basic.dart:129
E/flutter (5856): #1 FlutterRustBridgeBase.executeNormal.<anonymous closure> basic.dart:70
E/flutter (5856): <asynchronous suspension>
E/flutter (5856): #2 _HomeState.onChainBalance screens.dart:82
E/flutter (5856): <asynchronous suspension>
E/flutter (5856):
```

**Comment by BitcoinZavior** [comment]
Check logs please, and share them here too if possible

**Comment by anipy1** [comment]
```text
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:50488/MPp0G7FSSYE=/ws
I/flutter ( 7602): [+] Storage Path: /data/user/0/com.example.ldk_node_flutter_demo/files/satoshixyz
I/flutter ( 7602): [+] ldkNode's address: tb1q7cemqmy6fkv080djrpdwkdmxwgytw44xuhdh3u
E/flutter ( 7602): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Failed to conduct wallet operation., null)
E/flutter ( 7602): #0      FlutterRustBridgeBase._transformRust2DartMessage
basic.dart:129
E/flutter ( 7602): #1      FlutterRustBridgeBase.executeNormal.<anonymous closure>
basic.dart:70
E/flutter ( 7602): <asynchronous suspension>
E/flutter ( 7602): #2      _HomeState.onChainBalance
screens.dart:83
E/flutter ( 7602): <asynchronous suspension>
E/flutter ( 7602):
```

If you require any additional information, please let me know.

**Comment by anipy1** [comment]
Hi @BitcoinZavior, this problem has been fixed by changing the Esplora URL to 'https://mempool.space/testnet/api.' Now, it no longer throws the 'Failed to conduct wallet operation' exception and can sync the wallet as expected. Thanks to @kumulynja for pointing this out to me on Telegram.

**Comment by anipy1** [comment]
However, I still have one doubt. So, basically, when we're building for mainnet or testnet, should we change the address to our external IPv4 address and the port to 9735 which is assigned to the Bitcoin Lightning Network, right?

I did set the address and port this way in the LDK configurations, something like this:

```dart
  buildNode(String mnemonic) async {
    final directory = await getApplicationSupportDirectory();
    final ipAddr = await IpAddress.getIpv4();
    final storagePath = "${directory.path}/satoshixyz";
    const esploraUrl = 'https://mempool.space/testnet/api';
    final builder = ldk.Builder()
        .setEntropyBip39Mnemonic(mnemonic: ldk.Mnemonic(internal: mnemonic))
        .setListeningAddress(ldk.NetAddress.iPv4(addr: ipAddr, port: 9735))
        .setNetwork(ldk.Network.testnet)
        .setStorageDirPath(storagePath)
        .setEsploraServer(esploraServerUrl: esploraUrl);
    ldkNode = await builder.build();
    await start();
    await getListeningAddress();
  }
```

With the above setup, the app starts, but after a few seconds, it abruptly quits and shows an error like this:

```text
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56235/DiKexY6ZBZU=/ws

I/flutter ( 7365): [+] Storage Path: /data/user/0/com.example.ldk_node_flutter_demo/files/satoshixyz
F/libc    ( 7365): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 7438 (tokio-runtime-w), pid 7365 (de_flutter_demo)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2023-09-23 17:29:10+0530
pid: 7365, tid: 7438, name: tokio-runtime-w  >>> com.example.ldk_node_flutter_demo <<<
uid: 10163
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'Failed to bind to listen address/port - is something else already listening on it?'

    eax 00000000  ebx 00001cc5  ecx 00001d0e  edx 00000006
    edi f111e81e  esi b3071b70
    ebp f6be5b90  esp b3071b18  eip f6be5b99
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #03 pc 006b4c14  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #04 pc 006b4b29  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #05 pc 0075ec8d  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #06 pc 007613e4  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #07 pc 00737c1a  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #08 pc 00737be2  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #09 pc 00737cca  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #10 pc 0040ba13  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #11 pc 003f0fde  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #12 pc 00767724  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #13 pc 00766553  /data/app/~~H6flh3lrNxrDaHOfe

QfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #14 pc 0076e9be  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #15 pc 0076a307  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #16 pc 00769f84  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #17 pc 0076a9b2  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #18 pc 007626e3  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
      #19 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #20 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
Lost connection to device.
Exited (sigterm)
```

I'm not sure, but I think there may be an issue with the node setup here.

**Comment by BitcoinZavior** [comment]
> Hi @BitcoinZavior, this problem has been fixed by changing the Esplora URL to 'https://mempool.space/testnet/api.' Now, it no longer throws the 'Failed to conduct wallet operation' exception and can sync the wallet as expected. Thanks to @kumulynja for pointing this out to me on Telegram.

That’s great!
So it was a sync issue caused by blockstream url rate limiting you or probably wrong esplora url.

**Comment by BitcoinZavior** [comment]
> Thanks to @kumulynja for pointing this out to me on Telegram.

@kumulynja to the rescue 👍

**Comment by anipy1** [comment]
> However, I still have one doubt. So, basically, when we're building for mainnet or testnet, should we change the address to our external IPv4 address and the port to 9735 which is assigned to the Bitcoin Lightning Network, right?
> 
> I did set the address and port this way in the LDK configurations, something like this:
> 
> ```dart
>   buildNode(String mnemonic) async {
>     final directory = await getApplicationSupportDirectory();
>     final ipAddr = await IpAddress.getIpv4();
>     final storagePath = "${directory.path}/satoshixyz";
>     const esploraUrl = 'https://mempool.space/testnet/api';
>     final builder = ldk.Builder()
>         .setEntropyBip39Mnemonic(mnemonic: ldk.Mnemonic(internal: mnemonic))
>         .setListeningAddress(ldk.NetAddress.iPv4(addr: ipAddr, port: 9735))
>         .setNetwork(ldk.Network.testnet)
>         .setStorageDirPath(storagePath)
>         .setEsploraServer(esploraServerUrl: esploraUrl);
>     ldkNode = await builder.build();
>     await start();
>     await getListeningAddress();
>   }
> ```
> 
> With the above setup, the app starts, but after a few seconds, it abruptly quits and shows an error like this:
> 
> ```
> √  Built build\app\outputs\flutter-apk\app-debug.apk.
> Connecting to VM Service at ws://127.0.0.1:56235/DiKexY6ZBZU=/ws
> 
> I/flutter ( 7365): [+] Storage Path: /data/user/0/com.example.ldk_node_flutter_demo/files/satoshixyz
> F/libc    ( 7365): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 7438 (tokio-runtime-w), pid 7365 (de_flutter_demo)
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
> Revision: '0'
> ABI: 'x86'
> Timestamp: 2023-09-23 17:29:10+0530
> pid: 7365, tid: 7438, name: tokio-runtime-w  >>> com.example.ldk_node_flutter_demo <<<
> uid: 10163
> signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
> Abort message: 'Failed to bind to listen address/port - is something else already listening on it?'
> 
>     eax 00000000  ebx 00001cc5  ecx 00001d0e  edx 00000006
>     edi f111e81e  esi b3071b70
>     ebp f6be5b90  esp b3071b18  eip f6be5b99
> backtrace:
>       #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
>       #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
>       #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
>       #03 pc 006b4c14  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #04 pc 006b4b29  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #05 pc 0075ec8d  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #06 pc 007613e4  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #07 pc 00737c1a  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #08 pc 00737be2  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #09 pc 00737cca  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #10 pc 0040ba13  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #11 pc 003f0fde  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #12 pc 00767724  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #13 pc 00766553  /data/app/~~H6flh3lrNxrDaHOfe
> 
> QfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #14 pc 0076e9be  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #15 pc 0076a307  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #16 pc 00769f84  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #17 pc 0076a9b2  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #18 pc 007626e3  /data/app/~~H6flh3lrNxrDaHOfeQfoBw==/com.example.ldk_node_flutter_demo-YPiKsrf3nnipB71TzZpteQ==/lib/x86/librust_ldk_node.so
>       #19 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
>       #20 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
> Lost connection to device.
> Exited (sigterm)
> ```
> 
> I'm not sure, but I think there may be an issue with the node setup here.

I asked [this](https://discord.com/channels/915026692102316113/978829624635195422/1155768160197279744) question today in the Lightning Dev Kit Discord server in the 'ldk-help' channel. @tnull responded, suggesting that "usually running a node that listens for inbound connections won't work on mobile. For one, as you already mentioned, that IP address won't be stable. But more importantly, many mobile providers won't even give you a 'real' IPv4 address; instead, they will put end devices behind NAT. So, if you don't want to go out of your way to implement hole punching or something similar, I'd generally recommend disabling the listening port on mobile devices and relying on outbound connections only."

The main issue of "Failed to conduct wallet operation" is solved by just changing the Esplora URL, so this particular issue is safe to close for now.

Thanks.
